# Guild ID
guild_id: 000

# Reddit credentials
reddit_client_id: ''
reddit_client_secret: ''
reddit_user_agent: ''

# Verification period (days)
verification_period: 5

# Reddit karma limit for Reddit submissions and comments
submission_karma_limit: 50
comment_karma_limit: 50

# Reddit karma threshold for verification
karma_threshold: 25

# FloofBot's ID
admin_bot_id: 000

# Minecraft channel
minecraft_channel_id: 000

# Minecraft death reaction
death_reaction_id: 000
