api_key: ""
server: "http://api.wolframalpha.com/v2/query"

# Show ads
ads: true
# Show ads every x uses
ad_uses: 15

# Client defaults
default_ip: "192.168.0.1"
default_units: "nonmetric"
scan_timeout: ""
pod_timeout: ""
format_timeout: ""
